### PR TITLE
Minor corrections in spec

### PR DESCRIPTION
**Pull request by hussainnm**
- Introduction
 Change to curly quotes from straight quotes
 Change document name to reflect current name
 Change version to 4.0
 Refer to earlier versions as Enterprise JavaBeans
- Overview
 Change version to 4.0
- DeploymentDescriptor
 Change version to ejb-jar_4_0.xsd
- Compatibility and Migration
 Change to EJB annotation instead of Enterprise Beans

I am proof reading the specification will add more commits as I find issues. Everyone is welcome to add comments to this PR and I will fix it.

### CODE REVIEW

**Comment by jeanouii** [comment]
Thanks @hussainnm for the hard work on this specification.

**Comment by hussainnm** [comment]
@jeanouii What do you think about removing the What's new in EJB 3.x sections in Introduction.adoc

I feel these sections are not required and have a mix of old and new terms. For e.g 

i. JAX-RPC is changed to Jakarta XML RPC
ii. javax.ejb.Timer is changed to jakarta.ejb.Timer
iii. JMS is referred to as Jakarta Messaging

You can voice your views on the mailing list[1]

[1] https://www.eclipse.org/lists/ejb-dev/msg00120.html

**Review by tkburroughs — APPROVED** [review]
These changes look good to me; is this one ready to merge?

**Comment by jeanouii** [comment]
@tkburroughs Hussain has been adding to it until very recently but indeed it looks good. I'll go ahead and merge today.

**Pull request merged**
